### ISSUE TITLE
documentation link not working

### ISSUE THREAD

**Issue by floriandierickx** [Spine-project/Spine-Model#1]
Just a quick notice/question: could you update the link to the documentation in readme.md ? Thanks!

**Comment by ererkka** [comment]
Thanks for noticing! We’ll work on that. Apparently the build docs have not been checked in.

**Comment by manuelma** [comment]
The link is now working (actually the former link was replaced by a badge on top of the page). Only the main function (`JuMP_all_out`) is now documented, but more to come.
